name: atmos_binary_buffer
version: 0.16.4
description: "Dart helper package to work with binary buffers by Atom735"
repository: https://github.com/Atom735/atmos_binary_buffer
environment:
  sdk: ">=2.16.1 <3.0.0"

dev_dependencies:
  atmos_lints: ^0.16.1
